name: Reuse artifact
on:
  workflow_call:
    inputs:
      artifact_name:
      required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.artifact_name }}

      - name: deploy
        run: echo "deploying..."
  