# If test fails

name: conditional workflow
on:
  push:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
      
      - name: test
        id: run-tests
        run: npm run test
      
      - name: Upload test fail
        if: steps.run-tests.outcome == 'failure'
        run: echo "uploading to test....."

      - name: upload test success
        if: steps.run-tests.outcome == 'success'
        run: echo "success"