# If test fails

name: conditional workflow
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
      
      - name: test
        id: run-tests
        run: npm run test
      
      - name: Upload test fail
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v7
        with:
          name: index-html
          path: index.html

      - name: upload test success
        if: success() && steps.run-tests.outcome == 'success'
        run: echo "success"


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: dist


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v7
        with:
          name: dist-files      
      
      - name: deploy
        run: echo "deploying..."


  report:
    needs: [test, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: report failure
        if: failure()
        run: "failed"