name: JOB output and Dependency caching
on:
  workflow_dispatch:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      script_file: ${{ steps.build_output.outputs.script_file }}
    steps:
      - name: Fetch repo
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'
      
      - name: Cache npm dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: output prod js file
        id: build_output
        # run: echo "script_file=$(find dist -type f -name '*.js' -exec basename {} \;)" >> $GITHUB_OUTPUT
        run: echo "script_file=$(find dist -type f -name '*.js' | head -n 1 | xargs basename)" >> $GITHUB_OUTPUT

      - name: Upload to artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-files
          path: dist

      - name: Testing the project
        run: npm run test
      # - name: Set Build output
      #   id: build_output
      #   run: echo "script-file="
  deploy:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      d_script_file: ${{ steps.build_files.outputs.d_script_file }}
    steps:
      - name: Fetch repo
        uses: actions/checkout@v6

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Cache npm dependencies
        uses: actions/cache@v5
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci


      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: build-files
          path: dist

      - name: debug
        run: |
          ls
          ls dist
      - name: Get name of script file
        id: build_files
        # run: echo "d_script_file=$(find deploy -type f -name '*.js' -exec basename {} \;)" >> $GITHUB_OUTPUT
        run: echo "d_script_file=$(find dist -type f -name '*.js' | head -n 1 | xargs basename)" >> $GITHUB_OUTPUT


      - name: Debug outputs
        run: |
          echo "Build Output: ${{ needs.build.outputs.script_file }}"
          echo "Deploy Output: ${{ steps.build_files.outputs.d_script_file }}"

      - name: Validate the script file and deploy
        if: ${{ needs.build.outputs.script_file == steps.build_files.outputs.d_script_file }}
        run: echo "deploying"

